export const quotes = [
  { text: "It is not that we have a short time to live, but that we waste a great deal of it.", author: "Seneca" },
  { text: "You could leave life right now. Let that determine what you do and say and think.", author: "Marcus Aurelius" },
  { text: "The impediment to action advances action. What stands in the way becomes the way.", author: "Marcus Aurelius" },
  { text: "We suffer more in imagination than in reality.", author: "Seneca" },
  { text: "Waste no more time arguing what a good man should be. Be one.", author: "Marcus Aurelius" },
  { text: "He who fears death will never do anything worthy of a living man.", author: "Seneca" },
  { text: "The first step: don't be anxious. Nature controls it all.", author: "Marcus Aurelius" },
  { text: "Begin at once to live, and count each separate day as a separate life.", author: "Seneca" },
  { text: "No man is free who is not master of himself.", author: "Epictetus" },
  { text: "Make the most of yourself, for that is all there is of you.", author: "Ralph Waldo Emerson" },
  { text: "The trouble is, you think you have time.", author: "Buddha" },
  { text: "Death is not the greatest loss in life. The greatest loss is what dies inside us while we live.", author: "Norman Cousins" },
  { text: "Tell me, what is it you plan to do with your one wild and precious life?", author: "Mary Oliver" },
  { text: "We're all just walking each other home.", author: "Ram Dass" },
  { text: "In the end, it's not the years in your life that count. It's the life in your years.", author: "Abraham Lincoln" },
  { text: "Do not go gentle into that good night. Rage, rage against the dying of the light.", author: "Dylan Thomas" },
  { text: "Time you enjoy wasting is not wasted time.", author: "Marthe Troly-Curtin" },
  { text: "The bad news is time flies. The good news is you're the pilot.", author: "Michael Altshuler" },
  { text: "Life is what happens when you're busy making other plans.", author: "John Lennon" },
  { text: "Almost everything will work again if you unplug it for a few minutes, including you.", author: "Anne Lamott" },
  { text: "You only live once, but if you do it right, once is enough.", author: "Mae West" },
  { text: "Life is short. Eat dessert first.", author: "Jacques Torres" },
  { text: "I'm not afraid of death; I just don't want to be there when it happens.", author: "Woody Allen" },
  { text: "The fear of death follows from the fear of life. A man who lives fully is prepared to die at any time.", author: "Mark Twain" },
  { text: "I would rather die a meaningful death than to live a meaningless life.", author: "Corazon Aquino" },
]
